[package]
name = "rack-director"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
clap = { version = "4.5.40", features = ["derive"] }
log = { version = "0.4.27", features = ["kv"] }
rusqlite = { version = "0.36.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
std-logger = "0.5.7"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "net", "macros", "sync", "signal", "fs", "time", "io-util"] }
rand = "0.8"
ipnet = "2.9"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tempfile = "3.12"
tokio-test = "0.4"
tower = { version = "0.4", features = ["util"] }
