# RHEL 10 Kickstart - generated by rack-director
# OS: {{ os.name }} {{ os.version }}
# Device: {{ device.uuid }}

install
text
reboot

clearpart --none

# Network
network --bootproto=static --ip={{ device.ip_address }} --netmask={{ device.netmask }} --gateway={{ device.gateway }} --nameserver={{ device.dns_servers }} --hostname={{ device.hostname }} --device={{ device.mac_address }}

# Pre-existing partitions (created by partition_disks action).
# --noformat preserves existing data; --onpart references the pre-created partition.
# Partitions with no mount_point (biosboot, LVM PVs) are omitted.
{{#each partitions}}{{#if this.mount_point}}{{#unless this.volume_group}}
part {{ this.mount_point }} --fstype="{{ this.filesystem }}" --onpart={{ this.device_name }} --noformat
{{/unless}}{{/if}}{{/each}}

# LVM: declare pre-existing VGs and LVs.
# Each unique VG is declared once; logvol entries reference pre-existing LVs.
{{#each logical_volumes}}{{#if this.mount_point}}
logvol {{ this.mount_point }} --vgname={{ this.vg_name }} --name={{ this.lv_name }} --fstype={{ this.filesystem }} --noformat --useexisting
{{/if}}{{/each}}

bootloader --location=mbr

%packages
@base
{{ role.name }}
%end

%post
echo "rack-director-provisioned" > /etc/rack-director
%end
